apiVersion: v1
kind: Service
metadata:
  name: nginx-v2
  labels:
    app: nginx-v2
spec:
  ports:
    - port: 80
  selector:
    app: nginx-v2
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-v2
  labels:
    app: nginx-v2
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-v2
        tier: frontend
    spec:
      containers:
      - image: nginx
        name: nginx-v2
        ports:
        - containerPort: 80
          name: nginx-v2
